---

- name: "configuration play." 
  hosts: localhost
  connection: local
  user: ubuntu
  become: true
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      shell: |
        /usr/bin/test -e /usr/bin/python3 || (/usr/bin/apt -y update && /usr/bin/apt install -y python3)
      changed_when: false
      
  tasks:

    - name: "Install Node.js 13"
      shell: |
        # Install Node.js LTS version as our base Node.js version
        curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
        sudo apt-get install -y nodejs

        # Use n version manager to use Node.js v13.8.0
        sudo npm install -g n
        sudo n 13.8.0

    - name: "Install PM2 Globally"
      npm:
        name: pm2
        global: yes

  roles:
#    - configure-server
#    - configure-prometheus-node-exporter