---
- name: Creates backend directory
  file:
    path: ~/backend-app
    state: directory

- name: Copy and unarchive artifact
  unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend-app

- name: Start PM2
  shell: |
    cd ~/backend-app
    npm i

- name: Start PM2
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print msg
  debug:
  msg: "{{execute_node.stdout_lines}}"

- name: configure pm2 to saas
  become: true
  shell: |
    env PATH=$PATH:usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu